### ISSUE TITLE
RuntimeError: the number of sizes provided       must be greater or equal to the number of dimensions in the tensor at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensor.c:290

### ISSUE THREAD

**Issue by c0nn3r** [jihunchoi/recurrent-batch-normalization-pytorch#3]
Hello, I get this error when I try to replace the LSTM in the language model with the modified (but normal) version found in this repo. Do you have idea where I should look to fix it? I would love to make a PR, but really having a hard time debugging this.

The error seems to happen on this line:
```
mask = (time < length).float().unsqueeze(1).expand_as(h_next)
```

**Comment by jihunchoi** [comment]
Hi, I can't give you a right solution just from information you provided, however it seems that the error comes from "expand" function.
I think printing sizes of `time`, `length`, and `h_next` and then checking if there exists mismatch would help.

**Comment by jihunchoi** [comment]
I close this, since it seems that this is not related to the recurrent BN implementation.
Please open a new issue if you are still having the problem.
